version: "3.1"

services:

  mariadb:
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - ./mariadb.env

  matomo:
    image: matomo
    depends_on:
      - mariadb
    restart: always
    volumes:
#     - ./config:/var/www/html/config
#     - ./logs:/var/www/html/logs
      - matomo:/var/www/html
    env_file:
      - ./matomo.env
    ports:
      - 8081:80

  xwiki:
    image: "xwiki:lts-mysql-tomcat"
    depends_on:
      - xwiki-mysql-db
    restart: always      
    volumes:
      - xwiki-data:/usr/local/xwiki      
    env_file:
      - ./xwiki.env
    ports:
      - 8080:8080      

  xwiki-mysql-db:
    image: "mysql:5.7"
    restart: always
    command: --max-allowed-packet=64MB
    volumes:
      # Download xwiki.cnf from: https://raw.githubusercontent.com/xwiki-contrib/docker-xwiki/master/11/mysql-tomcat/mysql/xwiki.cnf
      # Download init.sql from: https://raw.githubusercontent.com/xwiki-contrib/docker-xwiki/master/11/mysql-tomcat/mysql/init.sql
      - ./xwiki.cnf:/etc/mysql/conf.d/xwiki.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    env_file:
      - ./mysql.env

volumes:
  db:
  matomo:
  mysql-data:
  xwiki-data: